### ISSUE TITLE
Handle non-terminating programs better

### ISSUE THREAD

**Issue by kavigupta** [rahularya50/scheme_interpreter_personal#1]
The way this software handles non-terminating programs could be better.

I suggest allowing the user to cancel programs from the run terminal within the webapp, perhaps by trapping Ctrl+C, or perhaps by adding an explicit stop button (a la IntelliJ/Eclipse)

**Comment by rahularya50** [comment]
Out of interest, will you just raise a SchemeError when the stop button / Ctrl-C is pressed? That would probably be simplest, since it wouldn't require any changes to the debugging logger or core interpreter.

**Comment by kavigupta** [comment]
Resolved.
