### ISSUE TITLE
Brackets and parens should not match with each other

### ISSUE THREAD

**Issue by kavigupta** [rahularya50/scheme_interpreter_personal#117]
This works but shouldn't

```
>>> '[1 2 3)
(1 2 3)
```

**Comment by kavigupta** [comment]
See also

https://github.com/Cal-CS-61A-Staff/berkeley-cs61a/issues/2418
https://github.com/Cal-CS-61A-Staff/dart_scheme/issues/90

**Comment by rahularya50** [comment]
...it doesn't work?

```
scm> '[1 2 3)
Unexpected token: ')'
```

**Comment by kavigupta** [comment]
oh ok thanks!
