### ISSUE TITLE
Block special forms should always be multiple lines

### ISSUE THREAD

**Issue by kavigupta** [rahularya50/scheme_interpreter_personal#120]
Right now the way factorial is formatted is literally

```
(define (fact x)
  (if (zero? x) 1 (* x (fact (- x 1)))))
```

this is hard to read. We should force block special forms `define-function, if, let, ...` to span multiple lines

**Comment by rahularya50** [comment]
Even `(define (cadr x) (car (cdr x)))`?

**Comment by rahularya50** [comment]
Also, this is an interesting case.

I determine the length of an expression by counting the number of tokens that are not digits, and exclude `if`, `mu`, `lambda`, and a few other special forms from the count.

And I also limit each line to a maximum of 10 tokens.

So you've basically hit the worst possible scenario for the formatter.

**Comment by rahularya50** [comment]
Fixed by #123
