### ISSUE TITLE
Ctrl+W closes the whole editor

### ISSUE THREAD

**Issue by kavigupta** [rahularya50/scheme_interpreter_personal#14]
Not sure if this is fixable, but Ctrl+W should not close the entire editor, just the current code window.

**Comment by jathak** [comment]
Ctrl-W is always captured by the browser when running in a regular browser window. I believe you can capture it if you make a progressive web app, but the user would need to install it and set it to open as a window (I'm also not sure if pages served from localhost can be PWAs).

**Comment by mehrdadn** [comment]
I think it should close the whole editor. I haven't seen websites capture it (check out Google Apps Script for instance) so I don't expect them to.

**Comment by rahularya50** [comment]
Closed since we don't seem to want this behavior and it won't work in Chrome anyway.
