### ISSUE TITLE
Cut off stack trace serverside if it's too long

### ISSUE THREAD

**Issue by kavigupta** [rahularya50/scheme_interpreter_personal#28]
(I noticed this issue due to the ridiculously long stack traces for KeyboardInterrupts, but it applies generally as well)

the program

```
(define (loop n)
  (if (zero? n) (/ 1 0) (loop (- n 1))))

(loop 300)
```

generates a 1204 line traceback. The Python program

```
def loop(n):
    if n == 0: 1/0
    return loop(n - 1)
loop(300)
````

generates the traceback

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in loop
  File "<stdin>", line 3, in loop
  File "<stdin>", line 3, in loop
  [Previous line repeated 297 more times]
  File "<stdin>", line 2, in loop
ZeroDivisionError: division by zero
```

which is 8 lines long (the [] are actually in the output). We should probably do something similar; though since we annotate with the frame, a simple string match would be insufficient. I think in practice clipping out the intermediate part of a stack trace is completely fine.

**Comment by rahularya50** [comment]
Alright, I'll address this as part of the fix for #25.
