### ISSUE TITLE
The console should let you know if the results are stale once you've updated the file

### ISSUE THREAD

**Issue by kavigupta** [rahularya50/scheme_interpreter_personal#3]
To reproduce this "bug":

- type some code into the editor
- click run
- modfiy the code in the editor
- type something into the console dependent on the modified code
- the old code is run instead of the new code

I see 2 ways of fixing this

1. warn you in some way that the results are stale
2. re-run the code silently on every save.

**Comment by rahularya50** [comment]
This function doesn't work properly when the user's code can't be parsed. (Try setting "file.scm" to "(")

**Comment by rahularya50** [comment]
Fixed by #58
