### ISSUE TITLE
Stop button doesn't free memory

### ISSUE THREAD

**Issue by kavigupta** [rahularya50/scheme_interpreter_personal#47]
There's a memory leak (?) where if you run a command that eats a bunch of memory, it doesn't seem to free it when that command is terminated, or even when you hit `Run` again, which should reset everything in theory

**Comment by kavigupta** [comment]
Apparently this isn't actually an issue, python runs the gc on need

**Comment by rahularya50** [comment]
Not that it matters, but it's not even the gc. I tried running gc.collect() manually, and it still wouldn't release memory.
