### ISSUE TITLE
Make it so test cases automatically update themselves, and that you can't have two instances of the same test case open simultaneously.

### ISSUE THREAD

**Issue by rahularya50** [rahularya50/scheme_interpreter_personal#8]
Right now, if you rerun a test case, it'll open in a new window, rather than displacing the old one.

**Comment by kavigupta** [comment]
Was just about to post this :-)

**Comment by rahularya50** [comment]
Yeah, I've now added all the issues I had on my old bug tracker.

**Comment by kavigupta** [comment]
oh ok sounds good!

**Comment by rahularya50** [comment]
Fixed by #41
