### ISSUE TITLE
Unclear how environment works?

### ISSUE THREAD

**Issue by kavigupta** [rahularya50/scheme_interpreter_personal#9]
I tried opening HW10 and clicking the "Environments" button, and a console with the following tab popped up

![image](https://user-images.githubusercontent.com/3214932/52619695-3fdd2200-2e57-11e9-8adc-e7f2d65b53b2.png)

But like it didn't have any contents? Not sure how it works

**Comment by rahularya50** [comment]
Oh yeah, you need to hit "Run" before trying to debug or look at the environment diagrams. I'll add a separate issue for that.

**Comment by kavigupta** [comment]
Oh ok that would fix this.
